include: package:lints/recommended.yaml

analyzer:
  errors:
    depend_on_referenced_packages: error
  exclude:
    - test/fixtures/**

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
